import { dirname, join } from 'node:path'
import { Glob } from 'bun'

const SRC_DIR = join(import.meta.dir, '../src')

type BarrelConfig = {
	dir: string
	outputFile: string
}

const configs: BarrelConfig[] = [
	{ dir: 'commands', outputFile: 'src/commands/index.ts' },
	{ dir: 'events', outputFile: 'src/events/index.ts' },
]

async function generateBarrel(config: BarrelConfig): Promise<string> {
	const targetDir = join(SRC_DIR, config.dir)
	const glob = new Glob('*/index.ts')
	const files = await Array.fromAsync(glob.scan(targetDir))

	const modules = files
		.map((file) => {
			const dirName = dirname(file)
			return { name: dirName, path: `./${dirName}` }
		})
		.sort((a, b) => a.name.localeCompare(b.name))

	const header = '// This file is auto-generated by scripts/generate-barrels.ts\n// Do not edit manually\n\n'

	const exports = modules
		.map((mod) => {
			const exportName = mod.name.replace(/-([a-z])/g, (_, c) => c.toUpperCase())
			return `export { default as ${exportName} } from '${mod.path}'`
		})
		.join('\n')

	return `${header}${exports}\n`
}

async function main() {
	for (const config of configs) {
		const outputPath = join(import.meta.dir, '..', config.outputFile)
		const content = await generateBarrel(config)
		await Bun.write(outputPath, content)
		console.log(`Generated: ${config.outputFile}`)
	}
}

main()
