#!/usr/bin/env bun
/**
 * Barrel file generator
 *
 * Generates index.ts barrel files for commands and events directories.
 * Scans for subdirectories with index.ts and creates re-exports.
 *
 * Usage:
 *   bun scripts/generate-barrels.ts          # Check only (exits 1 if out of date)
 *   bun scripts/generate-barrels.ts --fix    # Generate and write files
 */

import { glob, readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'

const FIX_MODE = process.argv.includes('--fix')
const SRC_DIR = join(import.meta.dir, '../src')

// ANSI colors
const c = {
	reset: '\x1b[0m',
	bold: '\x1b[1m',
	dim: '\x1b[2m',
	red: '\x1b[31m',
	green: '\x1b[32m',
	yellow: '\x1b[33m',
	cyan: '\x1b[36m',
} as const

interface BarrelConfig {
	dir: string
	outputFile: string
}

const configs: BarrelConfig[] = [
	{ dir: 'commands', outputFile: 'src/commands/index.ts' },
	{ dir: 'events', outputFile: 'src/events/index.ts' },
]

interface GenerateResult {
	content: string
	modules: string[]
}

async function generateBarrel(config: BarrelConfig): Promise<GenerateResult> {
	const targetDir = join(SRC_DIR, config.dir)
	const files = (await Array.fromAsync(glob('*/index.ts', { cwd: targetDir }))).sort()

	const modules = files.map((file) => {
		const dirName = dirname(file)
		return { name: dirName, path: `./${dirName}` }
	})

	const header =
		'// This file is auto-generated by scripts/generate-barrels.ts\n// Do not edit manually\n\n'

	const exports = modules
		.map((mod) => {
			const exportName = mod.name.replace(/-([a-z])/g, (_, c) => c.toUpperCase())
			return `export { default as ${exportName} } from '${mod.path}'`
		})
		.join('\n')

	return {
		content: `${header}${exports}\n`,
		modules: modules.map((m) => m.name),
	}
}

function printTree(modules: string[]) {
	for (const [i, mod] of modules.entries()) {
		const isLast = i === modules.length - 1
		const prefix = isLast ? '└─' : '├─'
		console.log(`${c.dim}   ${prefix} ${c.yellow}${mod}${c.reset}`)
	}
}

async function main() {
	console.log(`\n${c.bold}${c.cyan}🔧 Barrel File Generator${c.reset}\n`)

	let hasChanges = false

	for (const config of configs) {
		const outputPath = join(import.meta.dir, '..', config.outputFile)
		const { content, modules } = await generateBarrel(config)

		let existing = ''
		try {
			existing = await readFile(outputPath, 'utf-8')
		} catch {
			// File doesn't exist
		}

		const isUpToDate = existing === content

		console.log(
			`${c.green}${c.bold}${config.outputFile}${c.reset} ${c.dim}(${modules.length} modules)${c.reset}`,
		)
		printTree(modules)

		if (!isUpToDate) {
			hasChanges = true
			if (FIX_MODE) {
				await writeFile(outputPath, content)
				console.log(`${c.green}   ✅ Updated${c.reset}`)
			} else {
				console.log(`${c.red}   ❌ Out of date${c.reset}`)
			}
		} else {
			console.log(`${c.dim}   ✓ Up to date${c.reset}`)
		}
		console.log()
	}

	console.log(`${c.dim}─────────────────────────────────${c.reset}`)

	if (!hasChanges) {
		console.log(`${c.green}${c.bold}✅ All barrel files are up to date${c.reset}\n`)
		return
	}

	if (FIX_MODE) {
		console.log(`${c.green}${c.bold}✅ All barrel files updated${c.reset}\n`)
	} else {
		console.log(`${c.red}${c.bold}❌ Barrel files are out of date${c.reset}`)
		console.log(`${c.dim}   Run with --fix to regenerate${c.reset}\n`)
		process.exit(1)
	}
}

main().catch(console.error)
